Adding asserts
- Moved not to test_utils

Signed-off-by: Andy Neff <andy@visionsystemsinc.com>

diff --git a/tests/run_tests b/tests/run_tests
--- a/tests/run_tests
+++ b/tests/run_tests
@@ -100,11 +100,27 @@ function run_all_tests_atexit()
   local sum=(-1 -1 -1 -1 -1 -1)
   if ! is_dir_empty "${TESTLIB_SUMMARY_DIR}"; then
     sum=($(awk '
+      function basename(file)
       {
-        for (i=1;i<=NF;i++) a[i]+=$i
+        sub(".*/", "", file)
+        return file
+      }
+      BEGIN{
+        ff_index=0
+      }
+      {
+        for (i=1;i<=NF;i++)
+        {
+          a[i]+=$i
+        }
+        if ($2 > 0)
+        {
+          f[ff_index++]=basename(FILENAME)
+        }
       }
       END{
         for (i=1;i<=NF;i++) printf a[i] " "
+        for (i=0;i<ff_index;i++) printf f[i] " "
         printf "\n"
       }' "${TESTLIB_SUMMARY_DIR}"/*))
   fi
@@ -144,6 +160,16 @@ function run_all_tests_atexit()
     echo -n "${TESTLIB_BOLD_COLOR}"
   fi
   printf "%d skipped${TESTLIB_RESET_COLOR}\n\n" ${sum[5]}
+
+  if [ "${#sum[@]}" -gt "6" ]; then
+    local x
+    echo "Tests with failures:" >&2
+    echo "--------------------" >&2
+    for (( x=6; x<${#sum[@]}; x++)); do
+      printf '%s\n' "${sum[x]}" >&2
+    done
+    echo ""
+  fi
 
   run_all_tests_cleanup
 
