Fix cleanup on source
Signed-off-by: Andy Neff <andy@visionsystemsinc.com>

diff --git a/linux/just_files/new_just b/linux/just_files/new_just
--- a/linux/just_files/new_just
+++ b/linux/just_files/new_just
@@ -1382,8 +1382,15 @@ if [ "${BASH_SOURCE[0]}" = "${0}" ] || [ "$(basename "${BASH_SOURCE[0]}")" = "${
   exec 1>&2 # Copy stderr to 1
   just_stdout=3 new_just ${@+"${@}"}
 
-  # Stop new_just_cleanup from being called twice
-  trap -- EXIT
-fi
+  # # Stop new_just_cleanup from being called twice
+  # trap -- EXIT
+else
+  # uwecho won't work right unless this file is kept around, so if being sourced,
+  # then vsi_common_dir is there, and use trap_chain
 
-new_just_cleanup
+  source "${VSI_COMMON_DIR}/linux/signal_tools.bsh"
+
+  trap_chain "new_just_cleanup exit" EXIT
+  trap_chain "new_just_cleanup int" INT
+  trap_chain "new_just_cleanup term" TERM
+fi
