use findin

diff --git a/linux/git_mirror b/linux/git_mirror
--- a/linux/git_mirror
+++ b/linux/git_mirror
@@ -7,6 +7,7 @@ if [ -z ${VSI_COMMON_DIR+set} ]; then
   VSI_COMMON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"
 fi
 source "${VSI_COMMON_DIR}/linux/dir_tools.bsh"
+source "${VSI_COMMON_DIR}/linux/findin"
 source "${VSI_COMMON_DIR}/linux/requirements.bsh"
 
 GIT_MIRROR_SOURCE="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd)"/"$(basename "${BASH_SOURCE[0]}")"
@@ -596,18 +597,16 @@ function _git_mirror_load_info()
   fi
 }
 
-# TODO: Replace with findin
 function _git_mirror_get_url()
 {
-  local index
-  for index in "${!repo_paths[@]}"; do
-    if [ "${repo_paths[$index]}" = "${1}" ]; then
-      echo "${repo_urls[$index]}"
-      return
-    fi
-  done
-  echo "Error: no entry found for: ${1}" >&2
-  return 1
+  local index="$(findin "${1}" "${repo_paths[@]}")"
+  if [ "${index}" -ge 0 ]; then
+    echo "${repo_urls[$index]}"
+    return 0
+  else
+    echo "Error: no entry found for: ${1}" >&2
+    return 1
+  fi
 }
 
 #**
