I'm pretty sure i did not want to filter here

diff --git a/linux/git_mirror b/linux/git_mirror
--- a/linux/git_mirror
+++ b/linux/git_mirror
@@ -838,9 +838,14 @@ function git_push_main()
           local refs=($("${GIT}" for-each-ref --format='%(refname)' | \
               grep -E "${GIT_MIRROR_PUSH_REFS_REGEX}" | \
               grep -v -E "${GIT_MIRROR_SKIP_REFS_REGEX}" -e '^refs/remotes' -e '^refs/stash'))
-          # xargs seems to try all args before returning an error code
-          if ! echo ${refs[@]+"${refs[@]}"} | grep -E "${GIT_MIRROR_FORCE_PUSH_REFS_REGEX}" | \
-              xargs "${GIT}" push "${repo_urls[$index]}"; then
+          # xargs tries all args before returning an error code; do this mostly
+          # for efficiency since each ref is re-pushed individually if this
+          # command fails
+          # per xarg's man page:
+          # "The xargs utility exits immediately (without processing any
+          # further input) if ... an invocation of utility exits with a value
+          # of 255", which is not the case if this push fails
+          if ! echo ${refs[@]+"${refs[@]}"} | xargs "${GIT}" push "${repo_urls[$index]}"; then
             # Re-run each push, forcing those that failed
             for ref in "${refs[@]}"; do
               if ! "${GIT}" push "${repo_urls[$index]}" "${ref}"; then
