Renamed just_wrap to Just_wrap

diff --git a/linux/Just_wrap b/linux/Just_wrap
--- a/linux/Just_wrap
+++ b/linux/Just_wrap
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
-#****F* just/just_wrap
+#****F* just/Just_wrap
 # NAME
-#   just_warp - Wrap files to create just environment
+#   Just_wrap - Wrap files to create just environment
 # USAGE
-#   just_wrap is typically used to write a one line (but long line) script. This
+#   Just_wrap is typically used to write a one line (but long line) script. This
 #   wrap script is then used every time you want to use your project environment
 #
 #   There are a total of four ways to use this wrap script.
@@ -28,16 +28,16 @@
 #   your wrap script would look something like this:
 #
 #   #!/usr/bin/env bash
-#   . "$(dirname "${BASH_SOURCE[0]}")"/external/vsi_common/linux/just_wrap "${BASH_SOURCE[0]}" my_project.env ${@+"${@}"}
+#   . "$(dirname "${BASH_SOURCE[0]}")"/external/vsi_common/linux/Just_wrap "${BASH_SOURCE[0]}" my_project.env ${@+"${@}"}
 #
 #   where my_project.env is the main project settings file.
 # AUTHOR
 #   Andy Neff
 #***
 
-   # Make sure set -eu doesn't fail      if just_wrap is wrapped and not being sourced
+   # Make sure set -eu doesn't fail      if Just_wrap is wrapped and not being sourced
 if ( ( [ ${#BASH_SOURCE[@]} -gt 1 ] && [ "${BASH_SOURCE[1]}" == "${0}" ] ) || \
-   # Or not being wrapped              and just_wrap is not being sourced
+   # Or not being wrapped              and Just_wrap is not being sourced
      ( [ ${#BASH_SOURCE[@]} == 1 ] && [ "${BASH_SOURCE[0]}" == "${0}" ] ) ) && \
    # With no argument (other than the environment variable)
    [ "$#" -le "1" ]; then
@@ -47,7 +47,7 @@ if ( ( [ ${#BASH_SOURCE[@]} -gt 1 ] && [ "${BASH_SOURCE[1]}" == "${0}" ] ) || \
     unset PROMPT_COMMAND
   fi
 
-  # If just_wrap was called directly
+  # If Just_wrap was called directly
   if [ "${#BASH_SOURCE[@]}" == "1" ]; then
     # Source this script and the env file with it.
     rc_file_line="source '${0}' '${1}'"
