Fix test-just_wrap was not callable
- just_wrap - Fixed unbound variables potential with BASH_SOURCE
- testlib.sh - Fixed potential unbound BASH_SOURCE in PS4

diff --git a/linux/just_wrap b/linux/just_wrap
--- a/linux/just_wrap
+++ b/linux/just_wrap
@@ -35,12 +35,10 @@
 #   Andy Neff
 #***
 
-being_sourced=
-
-   # If wrapped and not being sourced
-if ( [ "${BASH_SOURCE[1]}" == "${0}" ] || \
-   # Or not being wrapped              and not being sourced
-     ( [ "${#BASH_SOURCE[@]}" == "1" ] && [ "${BASH_SOURCE[0]}" == "${0}" ] ) ) && \
+   # Make sure set -eu doesn't fail      if just_wrap is wrapped and not being sourced
+if ( ( [ ${#BASH_SOURCE[@]} -gt 1 ] && [ "${BASH_SOURCE[1]}" == "${0}" ] ) || \
+   # Or not being wrapped              and just_wrap is not being sourced
+     ( [ ${#BASH_SOURCE[@]} == 1 ] && [ "${BASH_SOURCE[0]}" == "${0}" ] ) ) && \
    # With no argument (other than the environment variable)
    [ "$#" -le "1" ]; then
 
@@ -75,7 +73,7 @@ shift 1 # Toss that argument away, you're done with it
 
 #This works as long as you don't name this script 'bash'... SO DON'T CALL YOUR SCIPT BASH!!!
 #If main wrapper script was not source
-if [ "${BASH_SOURCE[1]}" == "${0}" ] || \
+if ( [ ${#BASH_SOURCE[@]} -gt 1 ] && [ "${BASH_SOURCE[1]}" == "${0}" ] ) || \
   # Or if there is no main wrapper script, and this script was not source
    ( [ "${#BASH_SOURCE[@]}" == "1" ] && [ "${BASH_SOURCE[0]}" == "${0}" ] ); then
   #Then execute the arguments!
