Improve missing Justfile error
Signed-off-by: Andy Neff <andy@visionsystemsinc.com>

diff --git a/linux/just b/linux/just
--- a/linux/just
+++ b/linux/just
@@ -241,10 +241,12 @@ if ! _just_load_justfile "${JUSTFILE}" && \
    [ "${1-}" != "--tab" ] && \
    [ "${1-}" != "--latest" ] && \
    [ "${1-}" != "--version" ]; then
-    echo "Can't find a suitable configuration file in this directory or any" >&2
-    echo "parent. Are you in the right directory?" >&2
+    source "${VSI_COMMON_DIR}/linux/colors.bsh"
+
+    echo "${RED}Can't find a suitable configuration file in this directory or any" >&2
+    echo "parent. Are you in the right directory?${NC}" >&2
     echo >&2
-    echo "Supported filenames: \"Justfile\" or value of \${JUSTFILE}" >&2
+    echo "Supported filenames: ${YELLOW}\"Justfile\" or value of \${JUSTFILE} (${JUSTFILE-unset})${NC}" >&2
     echo >&2
 fi
 
